# Reading the (CSV,JSON,PARQUET)datasets

# *Importing Libraries*

In [43]:
import pandas as pd

In [44]:
import os

In [45]:
import numpy as np

In [46]:
import json

In [47]:
pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\magima\anaconda3\ana\lib\site-packages (19.0.0)
Note: you may need to restart the kernel to use updated packages.

# *CSV dataset 1*

In [48]:
csv_path1="C:\\Users\\MAGIMA\\Documents\\Dharshini\\healthexp.csv"

# *Read CSV 1 dataset*

In [49]:
df_csv1=pd.read_csv(csv_path1)

In [50]:
df_csv1

     Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]

# *CSV dataset 2*

In [51]:
csv_path2="C:\\Users\\MAGIMA\\Documents\\Dharshini\\chickweight.csv"

# *Read CSV 2 dataset*

In [52]:
df_csv2=pd.read_csv(csv_path2)

In [53]:
df_csv2

     weight  Time  Chick  Diet
0        42     0      1     1
1        51     2      1     1
2        59     4      1     1
3        64     6      1     1
4        76     8      1     1
..      ...   ...    ...   ...
573     175    14     50     4
574     205    16     50     4
575     234    18     50     4
576     264    20     50     4
577     264    21     50     4

[578 rows x 4 columns]

# *CSV dataset 3*

In [54]:
csv_path3="C:\\Users\\MAGIMA\\Documents\\Dharshini\\taxis.csv"

# *Read CSV 3 dataset*

In [55]:
df_csv3=pd.read_csv(csv_path3)

In [56]:
df_csv3

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

# *JSON dataset 1*

In [57]:
json_path1="C:\\Users\\MAGIMA\\Documents\\Dharshini\\airports.json"

In [58]:
with open(json_path1,"r") as f:
    raw_data1=json.load(f)

# *Reading JSON 1 dataset*

In [59]:
df_json1=pd.json_normalize(raw_data1)

In [60]:
df_json1

                                            airports
0  [{'code': 'ATL', 'name': 'Hartsfield-Jackson A...

# *JSON dataset 2*

In [61]:
json_path2="C:\\Users\\MAGIMA\\Documents\\Dharshini\\file-extensions.json"

In [62]:
with open(json_path2,"r") as f:
    raw_data2=json.load(f)

# *Reading JSON 2 dataset*

In [63]:
df_json2=pd.json_normalize(raw_data2)

In [64]:
df_json2

                                          extensions
0  [{'extension': '.json', 'type': 'Data', 'mime_...

# *JSON dataset 3*

In [65]:
json_path3="C:\\Users\\MAGIMA\\Documents\\Dharshini\\http-status-codes.json"

In [66]:
with open(json_path3,"r") as f:
    raw_data3=json.load(f)

# *Reading JSON 3 dataset*

In [67]:
df_json3=pd.json_normalize(raw_data3)

In [68]:
df_json3

                                        status_codes
0  [{'code': 100, 'message': 'Continue', 'categor...

# *Parquet dataset 1*

In [69]:
parquet_path1="C:\\Users\\MAGIMA\\Documents\\Dharshini\\sample-parquet-files-sample-4.parquet"

# *Reading parquet 1 dataset*

In [70]:
df_parquet1=pd.read_parquet(parquet_path1,engine="pyarrow")

In [71]:
df_parquet1

       column0   column1
0        first      last
1        Jorge     Frank
2       Hunter    Moreno
3       Esther    Guzman
4       Dennis  Stephens
..         ...       ...
96       Brett    Miller
97    Adelaide    Phelps
98         Leo   Walters
99      Samuel   Schmidt
100  Elizabeth    Gordon

[101 rows x 2 columns]

# *Parquet dataset 2*

In [72]:
parquet_path2="C:\\Users\\MAGIMA\\Documents\\Dharshini\\sample-parquet-files-sample-5.parquet"

# *Reading parquet 2 dataset*

In [73]:
df_parquet2=pd.read_parquet(parquet_path2,engine="pyarrow")

In [74]:
df_parquet2

     column0  column1
0      first     last
1      Lewis   Taylor
2       Alan  Schultz
3       Dora  Carroll
4       Ryan   Daniel
..       ...      ...
296    Alvin   Snyder
297  Matilda    Silva
298    Ethan  Morales
299  Bernice   Cortez
300    Jimmy   Wright

[301 rows x 2 columns]

# *Parquet dataset 3*

In [75]:
parquet_path3="C:\\Users\\MAGIMA\\Documents\\Dharshini\\sample-parquet-files-sample-6.parquet"

# *Reading parquet 2 dataset*

In [76]:
df_parquet3=pd.read_parquet(parquet_path3,engine="pyarrow")

In [77]:
df_parquet3

      column0   column1
0       first      last
1        Edna      Moss
2      Harvey    Carter
3        Leah   Douglas
4     Ricardo     Owens
...       ...       ...
996    Donald      Paul
997    Amanda     Green
998    Myrtie    Walton
999      Todd  Johnston
1000    Essie      Carr

[1001 rows x 2 columns]